### ISSUE TITLE
Xbox App Not Responding To Inputs.

### ISSUE THREAD

**Issue by theoneaonly** [fqlx/XboxKeyboardMouse#139]
The executable itself runs fine and when "controller" is clicked, it will show that a green square when I use my keyboard. However, when I start to stream on my pc, it won't work. I can't press down arrows to go through the menus etc. What's the problem?

**Comment by DavidRieman** [comment]
Usually this is due to the addition of the XKM controller being an _additional_ controller, which the game thinks is another player, etc.  Usually you can regain control by hitting the button mapped to the Guide button, and you should see controls working there.  Slide left and Switch Profile to convince Xbox to let this controller be the main controller.  Depending on the game code and such, that might not work and you may have to physically disconnect or turn off the wireless controller you were using before (I just pop the batteries out for a moment to do so).

**Comment by NothonL** [comment]
@DavidRieman > Usually this is due to the addition of the XKM controller being an _additional_ controller, which the game thinks is another player, etc. Usually you can regain control by hitting the button mapped to the Guide button, and you should see controls working there. Slide left and Switch Profile to convince Xbox to let this controller be the main controller. Depending on the game code and such, that might not work and you may have to physically disconnect or turn off the wireless controller you were using before (I just pop the batteries out for a moment to do so).

Being that this is a recent response, do you have any idea if this is patched or not?  I can get my mnk to work for use of the homescreen but not the actual game itself.  Any pointers will help thank you!

**Comment by DavidRieman** [comment]
To further ensure the XKM virtual controller is the one driving any game, ensure XKM is set up before launching the game on the console, and only use the XKM to invoke the game's start menus.  If it is too late, keep in mind you can force quit games (https://support.xbox.com/en-US/xbox-one/apps/how-to-close-xbox-one-app-or-game) and relaunch it with the XKM controller.

**Comment by DavidRieman** [comment]
Closing with link to #102 to document the tips in a FAQ or whatnot - If you find things are still not working, please open a new issue with fresh details.  Thanks!
