### ISSUE TITLE
Resize Window

### ISSUE THREAD

**Issue by projectje** [fqlx/XboxKeyboardMouse#154]
![xboxcontroller](https://user-images.githubusercontent.com/6946109/53701839-3d8c3900-3e01-11e9-94a6-62ac7009f89d.PNG)

It seems I cant resize the window to change settings

**Comment by Nanquitas** [comment]
Hi, if it's because you have a high-dpi screen then yes, this app will not be displayed correctly (not properly supported).

Here's the solution to do basic scaling:
 - Right click on XboxKeyboardMouse.exe
 - Open Properties
 - Go to Compatibility Tab and change the high DPI scaling settings to System (enhanced)
 - Apply and enjoy

![hidpi](https://user-images.githubusercontent.com/13298129/53862806-c74a2b00-3fe8-11e9-98ae-93fade48c6c2.png)

**Comment by projectje** [comment]
check!
