### ISSUE TITLE
How do I custom map?

### ISSUE THREAD

**Issue by zeekw** [fqlx/XboxKeyboardMouse#25]
I can't figure out how to configure my own mapping for each controller button. Could you please explain?

**Comment by CallumCarmicheal** [comment]
Hello @zeekw there is a new GUI update that will be arriving soon although for this case i will be using old screenshots, the newer version should be easier to use. 

First, you will want to open the application:
![first you open the application](https://cloud.githubusercontent.com/assets/6545688/23181737/03f9d510-f86e-11e6-8fc9-057b8a91fd6b.PNG)

Then click the options button and when the form opens click "Add a preset"
![you next goto add a preset](https://cloud.githubusercontent.com/assets/6545688/23181763/214fb6ca-f86e-11e6-84c9-4666e7994b62.PNG)

After creating the preset goto Preset Manager -> Presets and select your preset and click "Load Profile"
![click the preset and click load](https://cloud.githubusercontent.com/assets/6545688/23181782/376d8450-f86e-11e6-800d-570058695e9c.PNG)

You next click "Input Mapper - Keyboard" *note as for right now, mouse mapper does not work and triggers are binded to Mouse1 and Mouse2, you would have to download the source and recompile it yourself to change that, sorry about this* 
![goto input mapper and select your keys](https://cloud.githubusercontent.com/assets/6545688/23181821/61a0e348-f86e-11e6-821d-d8ea44db0106.PNG)

Once you are done you want to reopen the Preset Options tab and click "Save - Settings and Input" on the right side under "Preset - {Name}" and on the right side under "Load Presets" click your preset and then press "Set as Active". This loads your preset and reloads the control scheme.
![save and set as active](https://cloud.githubusercontent.com/assets/6545688/23181923/b88aa46e-f86e-11e6-8a47-864e5e1035a0.PNG)

Please note, you will have to mess around a-ton with the mouse movement because it is really bad at the moment. Everything will be improved in future releases!

**Comment by zeekw** [comment]
Thank you so much for the quick reply! Unfortunately I still don't understand how to change the corresponding buttons for in the input mapper tab. For example, if I wanted to use the right-shift key (instead of the E key) for right-bumper. Could you explain this? Sorry if I'm just missing something.

**Comment by CallumCarmicheal** [comment]
Follow the tutorial up to the image where you can select/ see all the mapped buttons and then to change a button hover your mouse over the button and when the letter turns green double click, a popup should appear, enter in your key and then follow the rest of the tutorial to save the file and set it as the active controls.

**Comment by zeekw** [comment]
Thanks so much. Got it working.

**Comment by zeekw** [comment]
Could you direct me to the lines in the source which set the triggers to left/right click?

**Comment by fqlx** [comment]
Looks like line 269 in TranslateMouse.cs

**Comment by CallumCarmicheal** [comment]
Added feature in #27
