### ISSUE TITLE
Mouse Movement Not Working 

### ISSUE THREAD

**Issue by mouldyXD** [fqlx/XboxKeyboardMouse#29]
Keyboard and mouse clicks work perfectly but i can move the camera with my mouse any suggestions?

**Comment by CallumCarmicheal** [comment]
@mouldyXD could you be more in-depth, what do you mean?

**Comment by mouldyXD** [comment]
My mouse wont move my camera ive looked in the settings and cant find anything that will fix it.

**Comment by CallumCarmicheal** [comment]
Hmm that is a strange issue, what do you mean by camera? What game are you playing?

**Comment by mouldyXD** [comment]
The right stick i tested it on Overwatch couldn't get it to move

**Comment by mouldyXD** [comment]
Ive fixed it by running the 32bit version

**Comment by CallumCarmicheal** [comment]
Hmm, ill have to look into the issue for 64 bit then.

**Comment by CallumCarmicheal** [comment]
I have just tested the latest build that I had uploaded earlier today it seems to work fine for me. I can't tell what your issue was, if you continue to have issues please setup your streaming normally and then un-fullscreen the Xbox app and unhook your kb/mouse click the "Controller" button and view a live visual of what your controller is looking like and check if your sticks are moving. You will have to rehook back into the XBOX App to see them move. So you will have to require it to be windowed.
