### ISSUE TITLE
Mouse not smooth, sometimes acts to much like a joystick

### ISSUE THREAD

**Issue by Zt7903** [fqlx/XboxKeyboardMouse#41]
Hi, I have been using this for a day or two and the keyboard works greats but I'm just wondering if there is going to be an update to make the mouse more smooth like being on a Pc or if there is an option that I can change. Thanks!

**Comment by CallumCarmicheal** [comment]
Everyone time i have to apologise for this i feel really bad, no matter how many times we try to map the mouse to a joystick we cannot figure out how the translation would work so we try as much to emulate a joystick rather than how a mouse would naively interact with a game, this is a issue that i personally cannot figure out. If you know or know someone who maybe able to make a algorithm that would solve this issue, please send them our way.

**Comment by Zt7903** [comment]
No, no need to apologize I would never be able to make anything like this and I understand it hard, I remember when I was taking classes for this type of things. I was just wondering if I was doing something wrong

**Comment by CallumCarmicheal** [comment]
I've tried many things but nothing really comes close, i have tried to see if XIM or anything like that had open-source parts that i could incorporate but there was none.

**Comment by GameInGameOut** [comment]
Mine was like this in overwatch, however, I figured out that if I changed the controller mode, in the games controller settings, from dual zone to linear graph, it acted perfectly like a mouse. This programs great, thanks to the dev

**Comment by LordGaybar** [comment]
where did you change from dual zone to linear?
