### ISSUE TITLE
Contribution (GIMX converts mouse to joystick)

### ISSUE THREAD

**Issue by felipe57** [fqlx/XboxKeyboardMouse#42]
Hello good afternoon, I do not know if you ever came to look, but there is an open source project called GIMX, does it have some code that would help with the translation of the mouse?

**Comment by CallumCarmicheal** [comment]
I've been scouring through the source code of GIMX since you posted, it seems there are some ideas that i can use but im going to need a little time to find exactly what im looking for. 

The usual with all these types of project (Which there are few that convert mouse to joystick axis) it is hard to find where the mouse input is converted because of 1) The obscure way it was programmed, 2) A lot of source files to dig through and 3) They are taking input from HID devices which will make the naming scheme harder to search through.

**Comment by felipe57** [comment]
I understand, I hope you can find something to help with the translation of the mouse, congratulations for the work you have done so far, and I hope it continues, I believe you managed to make the mouse work smoothly. Thank you: D
