### ISSUE TITLE
Is lag low enough to play fps multiplayer?

### ISSUE THREAD

**Issue by parkgrrr** [fqlx/XboxKeyboardMouse#44]
I haven't purchased an Xbox yet, but is the lag for this app + the Xbox stream lag low enough to play multiplayer fps? I mostly want to play rainbow 6 siege with some friends, but I'm used to PC.

**Comment by CallumCarmicheal** [comment]
If you can get the mouse to work fine and not "seem" segmented (which is very hard to do at the moment), you can set the streaming quality to low (this will give you the best results for network bandwidth wise), you may want to plug the xbox into your pc through ethernet (this will allow a even faster connection than wireless) and set your internet to do a passthrough (check the support link below).

[Xbox Support: Connect your Xbox One to Xbox Live with a Windows PC instead of a router
](http://support.xbox.com/en-GB/xbox-one/networking/connect-live-using-pc)

If you have anymore issues or questions please ask away and reopen this issue.

side note: I mostly use the Raw Input + Sensitivity option and then turn my DPI all the way up, around 8000 should be pretty good (this depends on how many pixels X and Y you have), The xbox controller only reads to –32768 -> 32768. This means you would have to drag your mouse from the center 32768 pixels to get the analog stick to fully move, to combat this you will want to change the sensitivity from 100 to something that works for you.

Dont forget to change the ingame controller options as well, these can help to improve the experience!

**Comment by fqlx** [comment]
Not really.  The majority of the lag comes streaming (~50ms) and not app or SCP driver.
