### ISSUE TITLE
(Help Wanted) Error "SCP Bus failed to initialize" When opening

### ISSUE THREAD

**Issue by peeky007** [fqlx/XboxKeyboardMouse#52]
Hello, 
I try to open the "XboxKeyboardMouse 24 02 2017 - x86_64" File (My computer is x64) but it gives me this error:

"SCP Bus failed to initialize". 

Then I click "OK" and it gives me this error:

"System.IO.IOExeption: SCP Virtual Buse Device not found at ScpDriverInterface.ScpBus..ctor(Int32 instance) at XboxKeyboardMouse.Active.Create.Controller 

So I have installed SlimDx and downloaded ScpToolkit-master but it still doesnt work.

I have tried opening xbox app and streaming my console but still get same error. Also have tried that and opening the ScpToolKit and connecting and Xbox One controller but still have same error.

Please help I really like what you have created, as it seems other people can get it to work:):):):)

LOOK AT PICTURES BELOW IF IT HELPS

Thanks,

![error4](https://user-images.githubusercontent.com/32425720/31051442-447e4eb4-a6b4-11e7-805c-98919c28e92a.PNG)
![error in visual studios debug](https://user-images.githubusercontent.com/32425720/31051444-4485f4d4-a6b4-11e7-8629-5407eedb51a7.PNG)
![error](https://user-images.githubusercontent.com/32425720/31051443-4481bf90-a6b4-11e7-9912-7e4d80fe7f1e.PNG)
![error2](https://user-images.githubusercontent.com/32425720/31051445-4487c87c-a6b4-11e7-8958-f6a8ebacc502.PNG)
![error3](https://user-images.githubusercontent.com/32425720/31051446-44ebab26-a6b4-11e7-8fa8-564079afaada.PNG)

**Comment by CallumCarmicheal** [comment]
This issue happens when the Scp Toolkit has not initialized and connected the virtual device to the computer. 

So could you try opening start menu and search "ScpToolkit" and click the "ScpToolkit Updater" that will ensure that it is up-to-date.

Next could you open the "ScpToolkit Monitor (Legacy)" and check if it says something like Host Address: ....., Pad 1: DS3 ..... - USB FFFFFFFF Charging, that means the driver works and the virtual device should be showing up. If you do not see this: please run "ScpToolkit Driver Installer" and it will walk you through the driver setup process again.

Restart your computer and give it another go hopefully this will work.

---
If the fix above does not would could you please try to uninstall and then redownloading the latest release here: https://github.com/nefarius/ScpToolkit/releases/tag/v1.6.238.16010 and then restart your computer, and repeat the steps above.

**Comment by DavidRieman** [comment]
I ran into this too at first.  I don't know why the ScpToolkit Installer installs an "ScpToolkit Driver Installer", that you have to _manually_ follow up with finding and running afterwards...  Seems like the driver should have been part of the first installer... but there you have it.

The error handling for this error condition is revised to help others through this, thanks to a rapid PR approval and merge  :)
