### ISSUE TITLE
Smooth Mouse Movement

### ISSUE THREAD

**Issue by CobraLlig** [fqlx/XboxKeyboardMouse#55]
I noticed that you mentioned to have added smooth mouse movement, however no matter which setting I use I can't seem to get a feeling in game that feels like a true mouse control scheme. I was just wondering if this is a limitation of the process as it is essentially just mimicking a control and is not actually a mouse, or if there was something I was missing.

What settings have you used to achieve the most responsive mouse control in First Person Shooters for example?

**Comment by CallumCarmicheal** [comment]
I had achieved smooth movement in Halo 5 but the settings did not work for any other game, I jumped the gun when I pushed the update and did not test other games, the issue is that there is no way to have a global smooth movement because every game uses the joystick differently even if it's subtle. Sadly this is something I don't know if I'll be able to work out without any outside help who have experience converting mouse to joystick smoothly.

**Comment by DavidRieman** [comment]
Indeed, some games may use "dead zones" of different size and shape intended to eliminate near-but-not-zero readings that controllers give at rest.  Without a dead zone, you'd set a controller down and your aim cursor would slowly drift, due to minor manufactured sensor differences.  (To experiment, pick up a controller and just _barely_ tilt the sticks slowly and notice they have to move a bit before the game reacts with _any_ aim change.)  Because these dead zone solutions are common, users would probably assume the game is buggy when they saw such drift, so game devs will keep making them.  Dead zones are usually square or circular, meaning either each axis is remapped to zero out small values independently (square), or the vector is remapped to zero out small vector lengths.  So no matter what, since details like this vary by game - there would need to be some sort of per-game settings selection - which could store that game's discovered dead zone width/height (for square) or length (for circles).  Possibly other details would need to be stored per game, as advanced techniques to combat other game-specific joystick assists (weird accelerations and such) get figured out.

**Comment by Norava** [comment]
What were your settings for smooth movement Callum? I'm testing in Halo 5 and getting ALOT of jerkiness when I'm aiming.

**Comment by CallumCarmicheal** [comment]
@Norava i no longer have the configuration but the higher you have the polling rate the smoother the experience will feel but with the higher polling the less movement the application can pick up on so you need to increase your dpi or sensitivity.

**Comment by AlbertoMonteiro** [comment]
I tried it using in Fortnite game, but when I need small movements, to aim with highest precision, it doesnt work as expected. I "alt+tabed" and changed values, but nothing change.

**Comment by DavidRieman** [comment]
I've implemented a mouse engine which handles the dead zone as discussed in this thread.
