### ISSUE TITLE
Not working in streaming app

### ISSUE THREAD

**Issue by BawlzOnChin** [fqlx/XboxKeyboardMouse#68]
I believe i installed it correctly, whenever i click on the stream it turns green and shows buttons are working in preview but i get no input in the actual stream?

**Comment by CallumCarmicheal** [comment]
This is a common theme that is happening to other people but i am just unable to replicate this issue, are you using the Xbox App or Xbox Beta App?

**Comment by DavidRieman** [comment]
Usually it's that the "new controller" attached isn't the active controller in the game because the user started with a physical controller attached, etc.  If that's the issue, XboxKeyboardMouse's guide button (by default the ` key) will still be bringing up the guide where input will start working.  Then Switch profile -> select your gamertag, and boom... this virtual controller is now the active controller for your gamertag.

Hopefully that helps.  This issue is stale though, so I'm closing it.  (PS there's a new version available with bugfixes.)
