### ISSUE TITLE
KB / Mouse detects it but in streaming it does not move

### ISSUE THREAD

**Issue by adrianalex98** [fqlx/XboxKeyboardMouse#75]
I did all the steps that had to be done, but when I start streaming nothing moves.

**Comment by DavidRieman** [comment]
Be aware when streaming through the Xbox app (whether with a physical 360 controller attached to the PC, or this virtual one), that the controller typically does not automatically "replace" an existing controller/gamertag pairing on the Xbox One.  So if you've interacted with a game's menus or even logged into the game, chances are you just need to tell the Xbox One you want to start using _this_ controller instead of the one that is currently paired.  To do so: Bring up the system menu (with ` by default), select Sign In, and select your gamertag again.

**Comment by DavidRieman** [comment]
#139 now also has similar tips.  Closing this one; linking for reference.

**Comment by DavidRieman** [comment]
Actually, #102 to track
